#!/bin/bash
# SANGI PC Monitor - Quick Command Reference
# Save this for easy access to common commands

echo "🤖 SANGI PC Workspace Monitor - Quick Commands"
echo "================================================"
echo ""
echo "📍 Current Directory: $(pwd)"
echo ""
echo "🚀 Quick Start:"
echo "  python3 monitor.py              # Run monitor (foreground)"
echo "  python3 test.py                 # Test AWS connection"
echo "  python3 logs.py --tail          # Watch logs live"
echo ""
echo "📊 View Logs:"
echo "  python3 logs.py --summary       # Show statistics"
echo "  python3 logs.py --last 20       # Last 20 entries"
echo "  python3 logs.py --emotions      # Emotion distribution"
echo "  tail -f logs/workspace_monitor.log  # Raw activity log"
echo "  tail -f logs/mqtt_messages.log      # Raw MQTT log"
echo ""
echo "🔧 Service Control (requires sudo):"
echo "  sudo systemctl start sangi-workspace-monitor"
echo "  sudo systemctl stop sangi-workspace-monitor"
echo "  sudo systemctl status sangi-workspace-monitor"
echo "  sudo systemctl restart sangi-workspace-monitor"
echo "  sudo journalctl -u sangi-workspace-monitor -f"
echo ""
echo "🗂️  Files:"
echo "  config.json         # Configuration"
echo "  bin/                # All executable scripts"
echo "  certs/              # AWS IoT certificates"
echo "  logs/               # Activity and MQTT logs"
echo "  docs/               # Documentation"
echo ""
echo "📚 Documentation:"
echo "  cat README.md"
echo "  cat docs/AWS_IOT_SETUP.md"
echo "  cat docs/LOGGING_GUIDE.md"
echo ""
